<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

add_action ('genesis_before_content','custom_image');

function custom_image() {
	echo '<img class="top-bar" src="http://localhost/eliza/wp-content/themes/ek-theme/images/cominscoch.png">';
}
genesis();
